### ISSUE TITLE
LazyCell::borrow_with might be unsound

### ISSUE THREAD

**Issue by nox** [indiv0/lazycell#68]
Cf. [that mitochondria commit](https://github.com/nox/mitochondria/commit/05c798530b7167a0c81c647d79a570b6f1c35c4c), in which I remove a `&mut T` on the stack, which may be put back on the stack by the passed `f` if `OnceCell::init_once` is called again reentrantly.

@eddyb also raises the concern that the current code might drop uninitialised memory, because the result of `f()` isn't first bound to a variable on stack and instead is put directly in the `&mut T`.

**Comment by eddyb** [comment]
The `&mut T` is less of a concern right now, whereas adversarial `Drop` can ruin your day.
Also, you shouldn't ever overwrite an initialized value if you return a reference to it (see @nox' `is_none` check).

**Comment by indiv0** [comment]
Thanks for the issue and comments! It's kind of being discussed over at https://github.com/indiv0/lazycell/issues/66 already, so I'll close the issue in favour of moving discussion there.
